// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsesl1eruUT9tlqaKOte7jpmTW4T8d7sA',
    appId: '1:492993907357:web:27084425a189cf9a1ae274',
    messagingSenderId: '492993907357',
    projectId: 'food-donation-applicatio-1882e',
    authDomain: 'food-donation-applicatio-1882e.firebaseapp.com',
    databaseURL: 'https://food-donation-applicatio-1882e-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-applicatio-1882e.appspot.com',
    measurementId: 'G-V8C0CKG87J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8Q2bpishFEUUAsWGeIZ16OPh85Bu4d4',
    appId: '1:492993907357:android:0afbcc758cf072581ae274',
    messagingSenderId: '492993907357',
    projectId: 'food-donation-applicatio-1882e',
    databaseURL: 'https://food-donation-applicatio-1882e-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-applicatio-1882e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdKa7Zc-ZNAP07QqZ2qklt3dHRnmSi8NI',
    appId: '1:492993907357:ios:8be70f38a8f4f4931ae274',
    messagingSenderId: '492993907357',
    projectId: 'food-donation-applicatio-1882e',
    databaseURL: 'https://food-donation-applicatio-1882e-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-applicatio-1882e.appspot.com',
    iosClientId: '492993907357-liatc8dvj1vlgui2i7nkfcu3nntcavar.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
